<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d58d5c4d-b0c3-4ea9-8920-6b63012dffbf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.46" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="7.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
    <PackageReference Include="System.Speech" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\openai\OpenAI.SDK\OpenAI.csproj" />
    <ProjectReference Include="..\..\..\symbl-csharp-sdk\Sdk\SymblAISharp.csproj" />
    <ProjectReference Include="..\..\Agent\.NET 6.0\Technologai.csproj" />
  </ItemGroup>

</Project>
